Rails.application.routes.draw do
  get 'suelo/show'
  get 'suelo/create'
  get 'suelo/index'
  get 'suelo/delete'
  get 'productos_cuidado/show'
  get 'productos_cuidado/create'
  get 'productos_cuidado/index'
  get 'productos_cuidado/delete'
  get 'hongo/show'
  get 'hongo/create'
  get 'hongo/index'
  get 'hongo/delete'
  get 'elemento_quim/show'
  get 'elemento_quim/create'
  get 'elemento_quim/index'
  get 'elemento_quim/delete'
  get 'cultivo/show'
  get 'cultivo/create'
  get 'cultivo/index'
  get 'cultivo/delete'
  get 'cuidado/show'
  get 'cuidado/create'
  get 'cuidado/index'
  get 'cuidado/delete'
  get 'componentes_fisco/show'
  get 'componentes_fisco/create'
  get 'componentes_fisco/index'
  get 'componentes_fisco/delete'
  get 'caract_quimica/show'
  get 'caract_quimica/create'
  get 'caract_quimica/index'
  get 'caract_quimica/delete'
  get 'caract_fisica/show'
  get 'caract_fisica/create'
  get 'caract_fisica/index'
  get 'caract_fisica/delete'
  get 'campo/show'
  get 'campo/create'
  get 'campo/index'
  get 'campo/delete'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end
